version: "3.8"
services:
  web:
    build:
      context: ./frontend
    ports:
      - "${PORT:-80}:80"
    environment:
      - VITE_API_BASE_URL=/api/v1

  api:
    build:
      context: ./backend
    environment:
      - PORT=${INTERNAL_PORT:-5000}
      - NODE_ENV=production
