[build]
setup = [
    { cmd = "cd backend && npm install" }
]
build = [
    { cmd = "cd backend && npm run build" }
]
start = [
    { cmd = "cd backend && npm start" }
]

[detect]
include = ["backend/*"]