[build]
baseImage = "node:18"

setup = [
    { cmd = "cd backend && npm install" }
]

build = [
    { cmd = "cd backend && npm run build" }
]

start = { cmd = "cd backend && npm start" }

[detect]
language = "node"
include = ["backend/*"]
exclude = ["frontend"]