export const dict = {
  en: {
    app: {
      name: "My Web Application",
      description: "A sample web application",
      version: "1.0.0",
      copyright: "© 2023 My Company",
      url: "https://www.example.com",
      supportEmail: "support@example.com",
      allRightsReserved: "app.allRightsReserved",
    },
    auth: {
      login: {
        title: "Login",
        usernameLabel: "Username",
        passwordLabel: "Password",
        loginButton: "Login",
        forgotPassword: "Forgot Password?",
        successMessage: "Login successful!",
        errorMessage: "Invalid username or password.",
      },
      register: {
        title: "Register",
        usernameLabel: "Username",
        emailLabel: "Email",
        passwordLabel: "Password",
        confirmPasswordLabel: "Confirm Password",
        registerButton: "Register",
        successMessage: "Registration successful!",
        errorMessage: "Registration failed.",
      },
      passwordReset: {
        title: "Password Reset",
        emailLabel: "Email",
        resetPasswordButton: "Reset Password",
        successMessage: "Password reset email sent!",
        errorMessage: "Email not found.",
      },
      logout: {
        button: "Logout",
      },
    },
    user: {
      profile: {
        title: "Profile",
        usernameLabel: "Username",
        emailLabel: "Email",
        firstNameLabel: "First Name",
        lastNameLabel: "Last Name",
        updateButton: "Update Profile",
        successMessage: "Profile updated successfully!",
        errorMessage: "Error updating profile.",
      },
      settings: {
        title: "Settings",
        languageLabel: "Language",
        themeLabel: "Theme",
        notificationsLabel: "Notifications",
        saveButton: "Save Settings",
        successMessage: "Settings saved successfully!",
        errorMessage: "Error saving settings.",
      },
      roles: ["admin", "user", "guest"],
      status: ["active", "inactive"],
    },
    actions: {
      create: "Create",
      read: "Read",
      update: "Update",
      delete: "Delete",
      submit: "Submit",
      cancel: "Cancel",
      save: "Save",
      edit: "Edit",
      view: "View",
      search: "Search",
    },
    navigation: {
      home: "Home",
      profile: "Profile",
      settings: "Settings",
      dashboard: "Dashboard",
      about: "About",
      contact: "Contact",
    },
    errors: {
      "404": "Page not found",
      "500": "Internal server error",
      unauthorized: "Unauthorized access",
      forbidden: "Forbidden",
    },
    ui: {
      loading: "Loading...",
      empty: "No data available",
      back: "Back",
      next: "Next",
      previous: "Previous",
      confirm: "Confirm",
    },
    data: {
      table: {
        noData: "No data available in table",
        searchPlaceholder: "Search...",
        perPage: "Items per page",
      },
      pagination: {
        first: "First",
        last: "Last",
        previous: "Previous",
        next: "Next",
      },
    },
    notifications: {
      successPrefix: "Success: ",
      errorPrefix: "Error: ",
      warningPrefix: "Warning: ",
      infoPrefix: "Info: ",
    },
    profile: {
      picture: "Profile Picture",
      bio: "Bio",
      location: "Location",
      website: "Website",
      socialLinks: "Social Links",
      contactInfo: "Contact Information",
    },
    problem: {
      codeExample: "Code example",
      hints: "hints",
    },
    codeEditor: {
      placeholder: "Code goes here",
      lines: "lines",
      characters: "characters",
    },
    stats: {
      overall: "overall",
      detailed: "Detailed",
    },
  },
};
